# Generated by Django 4.1.3 on 2022-12-01 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrativo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fechaReserva",
                    models.DateTimeField(verbose_name="Fecha a la que se reserva"),
                ),
                (
                    "cantidad",
                    models.IntegerField(verbose_name="Tipo de emprendimiento"),
                ),
                ("valor", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="emprendimiento",
            name="menu",
        ),
        migrations.AddField(
            model_name="emprendimiento",
            name="productos",
            field=models.ManyToManyField(
                to="administrativo.producto", verbose_name="Productos"
            ),
        ),
        migrations.AlterField(
            model_name="foto",
            name="urlFoto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="fotoNegocio/",
                verbose_name="Imagen del negocio",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="fotoProducto/",
                verbose_name="Foto del Producto",
            ),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="fotoCategoria/",
                verbose_name="Foto del servicio",
            ),
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
        migrations.AddField(
            model_name="reserva",
            name="emprendimiento",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="administrativo.emprendimiento",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="producto",
            field=models.ManyToManyField(
                to="administrativo.producto", verbose_name="Producto a reservar"
            ),
        ),
    ]
