# Generated by Django 4.1.3 on 2022-12-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrativo", "0003_alter_reserva_emprendimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="nombreS",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nombre del Servicio",
            ),
        ),
    ]
